[window]
opacity = 0.8
blur = true
startup_mode = "Maximized"
decorations = "Transparent"

[font]
normal = { family = "RobotoMonoNerdFont", style = "Regular" }
size= 15

[cursor]
style = { shape = "Block", blinking = "Always" }

[mouse]
hide_when_typing = true
