import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
opacity = 0.8
blur = true
startup_mode = "Maximized"
decorations = "Transparent"

[font]
normal = { family = "RobotoMonoNerdFont", style = "Regular" }
size= 15

[cursor]
style = { shape = "Block", blinking = "Always" }

[mouse]
hide_when_typing = true

[env]
TERM = "xterm-256color"
