#!/usr/bin/env bash

set -e

EFAULT_CONFIG_PREFIX="default"
CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if type yay >/dev/null 2>&1; then
    PLUGIN_DIR="dotbot-yay"
elif type apt-get >/dev/null 2>&1; then
    PLUGIN_DIR="dotbot_plugin_aptget"
fi

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

for conf in ${DEFAULT_CONFIG_PREFIX} ${@}; do
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${conf}${CONFIG_SUFFIX}" \
        --plugin-dir "$PLUGIN_DIR"
done
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
