# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]

prepend_keymap = [
    { on = "<C-s>", run = "shell $SHELL --block --confirm", desc = "Open shell here" },

    # Hopping
    { on = "e", run = "arrow prev", desc = "Move cursor up" },
    { on = "n", run = "arrow next", desc = "Move cursor down" },

    { on = "<A-e>", run = "arrow -5", desc = "Move cursor up" },
    { on = "<A-n>", run = "arrow 5", desc = "Move cursor down" },

    { on = "H", run = "back", desc = "Go back to the previous directory" },
    { on = "I", run = "forward", desc = "Go forward to the next directory" },

    # Seeking
    { on = "E", run = "seek -5", desc = "Seek up 5 units in the preview" },
    { on = "N", run = "seek 5", desc = "Seek down 5 units in the preview" },

    # Operation
    { on = "l", run = "link", desc = "Symlink the absolute path of yanked files" },
    { on = "L", run = "link --relative", desc = "Symlink the relative path of yanked files" },
    { on = "<Backspace>", run = "hidden toggle", desc = "Toggle the visibility of hidden files" },

    # Find
    { on = "k", run = "find_arrow", desc = "Go to the next found" },
    { on = "K", run = "find_arrow --previous", desc = "Go to the previous found" },

    # sudo cp/mv
    { on = ["R", "p", "p"], run = "plugin sudo --args='paste'", desc = "sudo paste" },
    # sudo cp/mv --force
    { on = ["R", "P"], run = "plugin sudo --args='paste -f'", desc = "sudo paste" },
    # sudo mv
    { on = ["R", "r"], run = "plugin sudo --args='rename'", desc = "sudo rename" },
    # sudo ln -s (absolute-path)
    { on = ["R", "l"], run = "plugin sudo --args='link'", desc = "sudo link" },
    # sudo ln -s (relative-path)
    { on = ["R", "L"], run = "plugin sudo --args='link -r'", desc = "sudo link relative path" },
    # sudo touch/mkdir
    { on = ["R", "a"], run = "plugin sudo --args='create'", desc = "sudo create" },
    # sudo trash
    { on = ["R", "d"], run = "plugin sudo --args='remove'", desc = "sudo trash" },
    # sudo delete
    { on = ["R", "D"], run = "plugin sudo --args='remove -P'", desc = "sudo delete" },

    # plugin what-size
    { on = [ "c", "s", ], run = "plugin what-size", desc = "Calc size of selection or cwd" },

    # plugin restore
    { on = "u", run = "plugin restore", desc = "Restore last deleted files/folders" },
    # or du like me
    # { on = [ "d", "u", ], run = "plugin restore", desc = "Restore last deleted files/folders" },

    # plugin chmod
    { on = [ "c", "m", ], run = "plugin chmod", desc = "Chmod on selected files"},

    # plugin ouch
    { on = [ "c", "a", ], run = "plugin ouch", desc = "compress with ouch"},

    # plugin diff
    { on = [ "c", "d", ], run = "plugin diff", desc = "Diff the selected with the hovered file"},

    # plugin fast-enter
    { on = "i", run = "plugin fast-enter", desc = "Enter the subfolder faster, or open the file directly" },

    # plugin open-with-cmd
    { on = "O", run  = "plugin open-with-cmd --args=block", desc = "Open with command in the terminal" },

    # plugin max-preview
    { on = "T", run  = "plugin --sync max-preview", desc = "Maximize or restore preview" },

]

[tasks]

prepend_keymap = [
    { on = "e", run = "arrow prev", desc = "Move cursor up" },
    { on = "n", run = "arrow next", desc = "Move cursor down" },
]

[select]

prepend_keymap = [
    { on = "e", run = "arrow prev", desc = "Move cursor up" },
    { on = "n", run = "arrow next", desc = "Move cursor down" },
]

[spot]

prepend_keymap = [
	{ on = "e", run = "arrow prev", desc = "Previous line" },
	{ on = "n", run = "arrow next", desc = "Next line" },
	{ on = "h", run = "swipe prev", desc = "Swipe to previous file" },
	{ on = "i", run = "swipe next", desc = "Swipe to next file" },
]

[pick]

prepend_keymap = [
	{ on = "e", run = "arrow prev", desc = "Previous option" },
	{ on = "n", run = "arrow next", desc = "Next option" },
]

[input]

prepend_keymap = [
    # Mode
	{ on = "l", run = "insert",                          desc = "Enter insert mode" },
	{ on = "L", run = [ "move first-char", "insert" ],   desc = "Move to the BOL, and enter insert mode" },
    # Character-wise movement
    { on = "h", run = "move -1", desc = "Move back a character" },
    { on = "i", run = "move 1", desc = "Move forward a character" },

    # Word-wise movement
    { on = "j",     run = "forward --end-of-word",       desc = "Move forward to the end of the current or next word" },
	{ on = "J",     run = "forward --far --end-of-word", desc = "Move forward to the end of the current or next WORD" },
]

[cmp]

prepend_keymap = [
    { on = "<A-e>", run = "arrow -1", desc = "Move cursor up" },
    { on = "<A-n>", run = "arrow 1", desc = "Move cursor down" },
]

[help]

prepend_keymap = [
    # Navigation
    { on = "e", run = "arrow -1", desc = "Move cursor up" },
    { on = "n", run = "arrow 1", desc = "Move cursor down" },
]
