# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/02b2ae69-5f98-46d7-ad1f-61b823d76f96";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2397-B733";
      fsType = "vfat";
    };

  fileSystems."/mnt/diska" =
    { device = "/dev/disk/by-uuid/f6cf9993-786e-46c8-8ba6-3c6debbd27ff";
      fsType = "ext4";
    };

  fileSystems."/mnt/diskb" =
    { device = "/dev/disk/by-uuid/8388db88-6089-4bad-9fad-229c81f4e371";
      fsType = "ext4";
    };

  fileSystems."/mnt/diskc" =
    { device = "/dev/disk/by-uuid/1d80f4f1-252b-4f0b-92fb-abe11239bb21";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/15de7c2a-e091-4b55-89ae-2dc9eb24daa3"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
