bg="#111111"
set -g status-bg "$bg"
set -g status-fg "$text"
set -g status-right-length 140

set -g window-status-format "#[fg=$surface,bg=$bg]#[fg=$overlay,bg=$surface]#I #W#[fg=$surface,bg=$bg]#[default]"
set -g window-status-current-format "#[fg=$teal,bg=$bg]#[fg=$surface,bg=$teal,bold]#I #W#[fg=$teal,bg=$bg]#[default]"


net_status_format="#[fg=$blue,bg=$bg]#[fg=$surface,bg=$blue]#(bash $HOME/.config/tmux/status/net.sh) #[default]"
cpu_status_format="#[fg=$yellow,bg=$blue]#[fg=$surface,bg=$yellow] #(curl -s http://localhost:61208/api/4/cpu/total 2>/dev/null | jq '.total | round') #[default]"
mem_status_format="#[fg=$pink,bg=$yellow]#[fg=$surface,bg=$pink] #(curl -s http://localhost:61208/api/4/mem/percent 2>/dev/null | jq '.percent | round') #[default]"
tem_status_format="#[fg=$orange,bg=$pink]#[fg=$surface,bg=$orange] #(curl -s http://localhost:61208/api/4/sensors | jq -r '[.[] | select(.unit == \"C\") | .value] | add / length | round') #[default]"
disk_status_format="#[fg=$cyan,bg=$orange]#[fg=$surface,bg=$cyan]󰆓 #(curl -s http://localhost:61208/api/4/fs 2>/dev/null | jq '.[] | select(.mnt_point == \"/\") | .percent | round') #[default]"
time_format="#[fg=$surface,bg=$cyan]#[fg=$text,bg=$surface]%m-%d %H:%M#[default]"

set -g status-left ""
set -g status-right "\
$net_status_format\
$cpu_status_format\
$mem_status_format\
$tem_status_format\
$disk_status_format\
$time_format
