[window]
opacity = 0.9
blur = false
startup_mode = "Maximized"
decorations = "Transparent"

[font]
normal = { family = "RobotoMonoNerdFont", style = "Regular" }
size= 15

[cursor]
style = { shape = "Block", blinking = "Always" }

[mouse]
hide_when_typing = true

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
{ key = "C", mods = "Alt", action = "Copy" },
{ key = "V", mods = "Alt", action = "Paste" },
]
