dracula_bg="#282A36"
dracula_fg="#F8F8F2"
dracula_selection="#44475A"
dracula_comment="#6272A4"
dracula_red="#FF5555"
dracula_orange="#FFB86C"
dracula_yellow="#F1FA8C"
dracula_green="#50fa7b"
dracula_purple="#BD93F9"
dracula_cyan="#8BE9FD"
dracula_pink="#FF79C6"
dracula_bright_red="#FF6E6E"
dracula_bright_green="#69FF94"
dracula_bright_yellow="#FFFFA5"
dracula_bright_blue="#D6ACFF"
dracula_bright_magenta="#FF92DF"
dracula_bright_cyan="#A4FFFF"
dracula_bright_white="#FFFFFF"
dracula_menu="#21222C"
dracula_visual="#3E4452"
dracula_gutter_fg="#4B5263"
dracula_nontext="#3B4048"
dracula_white="#ABB2BF"
dracula_black="#191A21"

base="#191A21"
surface="#21222C"
surface1="#3B4048"
overlay="#3E4452"
overlay1="#44475A"
text="#F8F8F2"
subtext="#6272A4"
gray="#4B5263"
red="#FF6E6E"
pink="#FF79C6"
orange="#FFB86C"
yellow="#F1FA8C"
green="#69FF94"
teal="#50fa7b"
blue="#D6ACFF"
cyan="#8BE9FD"
purple="#BD93F9"
