gruvbox_fg="#ebdbb2"
gruvbox_bg="#282828"
gruvbox_bg_inactive="#232323"
gruvbox_alt_bg="#232323"
gruvbox_dark="#26292a"
gruvbox_accent="#806969"
gruvbox_dark_gray="#5c6370"
gruvbox_fg_gutter="#353d46"
gruvbox_context="#4b5263"
gruvbox_popup_back="#353535"
gruvbox_search_orange="#613214"
gruvbox_search_blue="#5e81ac"
gruvbox_gray="#5c6370"
gruvbox_light_gray="#abb2bf"
gruvbox_blue="#83a598"
gruvbox_dark_blue="#353535"
gruvbox_green="#adb026"
gruvbox_cyan="#749689"
gruvbox_red="#dc4934"
gruvbox_orange="#d65d0e"
gruvbox_light_red="#be5046"
gruvbox_yellow="#d79921"
gruvbox_yellow_orange="#d79921"
gruvbox_purple="#d3869b"
gruvbox_magenta="#D16D9E"
gruvbox_cursor_fg="#515052"
gruvbox_cursor_bg="#AEAFAD"
gruvbox_sign_add="#fabd2f"
gruvbox_sign_change="#83a598"
gruvbox_sign_delete="#94151b"
gruvbox_error_red="#F44747"
gruvbox_warning_orange="#e78a4e"
gruvbox_info_yellow="#FFCC66"
gruvbox_hint_blue="#4FC1FF"

base="#282828"
surface="#232323"
surface1="#26292a"
overlay="#353d46"
overlay1="#4b5263"
text="#ebdbb2"
subtext="#5e81ac"
gray="#5c6370"
red="#dc4934"
pink="#d3869b"
orange="#d65d0e"
yellow="#FFCC66"
green="#adb026"
teal="#83a598"
blue="#4FC1FF"
cyan="#749689"
purple="#D16D9E"
