onedark_black="#181a1f"
onedark_bg_d="#21252b"
onedark_bg0="#282c34"
onedark_bg1="#31353f"
onedark_bg2="#393f4a"
onedark_bg3="#3b3f4c"
onedark_bg_blue="#73b8f1"
onedark_bg_yellow="#ebd09c"
onedark_chalky="#e5c07b"
onedark_coral="#e06c75"
onedark_cyan="#56b6c2"
onedark_ivory="#abb2bf"
onedark_malibu="#61afef"
onedark_sage="#98c379"
onedark_stone="#5c6370"
onedark_violet="#c678dd"
onedark_whiskey="#d19a66"
onedark_light_grey="#848b98"
onedark_dark_cyan="#2b6f77"
onedark_dark_red="#993939"
onedark_dark_yellow="#93691d"
onedark_dark_purple="#8a3fa0"
onedark_diff_add="#31392b"
onedark_diff_delete="#382b2c"
onedark_diff_change="#1c3448"
onedark_diff_text="#2c5372"

base="#181a1f"
surface="#21252b"
surface1="#282c34"
overlay="#31353f"
overlay1="#393f4a"
text="#cdd6f4"
subtext="#2c5372"
gray="#848b98"
red="#e06c75"
pink="#c678dd"
orange="#e5c07d"
yellow="#ebd09c"
green="#98c375"
teal="#abb2bf"
blue="#73b8f1"
cyan="#56b6c2"
purple="#8a3fa0"
