tokyonight_bg="#222436"
tokyonight_bg_dark="#1e2030"
tokyonight_bg_dark1="#191B29"
tokyonight_bg_highlight="#2f334d"
tokyonight_blue="#82aaff"
tokyonight_blue0="#3e68d7"
tokyonight_blue1="#65bcff"
tokyonight_blue2="#0db9d7"
tokyonight_blue5="#89ddff"
tokyonight_blue6="#b4f9f8"
tokyonight_blue7="#394b70"
tokyonight_comment="#636da6"
tokyonight_cyan="#86e1fc"
tokyonight_dark3="#545c7e"
tokyonight_dark5="#737aa2"
tokyonight_fg="#c8d3f5"
tokyonight_fg_dark="#828bb8"
tokyonight_fg_gutter="#3b4261"
tokyonight_green="#c3e88d"
tokyonight_green1="#4fd6be"
tokyonight_green2="#41a6b5"
tokyonight_magenta="#c099ff"
tokyonight_magenta2="#ff007c"
tokyonight_orange="#ff966c"
tokyonight_purple="#fca7ea"
tokyonight_red="#ff757f"
tokyonight_red1="#c53b53"
tokyonight_teal="#4fd6be"
tokyonight_terminal_black="#444a73"
tokyonight_yellow="#ffc777"

base="#191B29"
surface="#222436"
surface1="#1e2030"
overlay="#2f334d"
overlay1="#444a73"
text="#c8d3f5"
subtext="#636da6"
gray="#3b4261"
red="#c53b53"
pink="#fca7ea"
orange="#ff966c"
yellow="#ffc777"
green="#c3e88d"
teal="#4fd6be"
blue="#82aaff"
cyan="#86e1fc"
purple="#c099ff"
